name: Create Runner
on:
  workflow_dispatch:
  inputs:
    actions:
      type: choice
      required: true
      options:
        - apply
        - destroy
jobs:
  runner:
    runs-on: ubuntu-latest 
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: Display the files
        run: |
          ls -ltrh
          pwd
      - name: Terraform seup
        uses: hashicorp/setup-terraform@v4

      - name: Terraform initializing
        run: terraform init --reconfigure
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.3.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: plan in terraform
        if: inputs.actions == 'apply'
        run: terraform plan

      - name: create infra
        if: inputs.actions == 'apply'
        run: terraform apply -auto-approve 
      - name: delete infra 
        if: inputs.actions == 'destroy'
        run: terraform destroy -auto-approve